### ISSUE TITLE
Error found to run the project using Next.js

### ISSUE THREAD

**Issue by breno-felipe** [React95/React95#253]
Ei, everyone!

The error happens whenever execute the project, running the command `yarn dev`.

At execute command `yarn dev` an error is return, conform image bellow.

The configuration to using the @React95 with Next.js was made at archive next-config.

Same with configuration the error happens.

![image](https://user-images.githubusercontent.com/50807243/115861595-5608a480-a409-11eb-88ec-b0e0cb724c2c.png)

**Comment by ggdaltoso** [comment]
Seems to be missing all png files into our dist folder 😨 

Would you like to open a PR fixing this?

**Comment by breno-felipe** [comment]
Yes, seems who this is the problems.

I can open yes

**Comment by ggdaltoso** [comment]
Hey, @kirkobyte! Look what's missing! :joy: 

I should like to take this opportunity to ask what you guys think would be nicer:
 1.  copy the PNG folder to the `dist` 
 2.  transform all PNG to base64, using [babel `inline-import-data-uri`](https://github.com/React95/React95/blob/master/packages/core/babel.config.js#L7) we already have

**Comment by ggdaltoso** [comment]
I've published 2 new version (alpha) to test this
 - @react95/core: 4.1.2-alpha.0
 - @react95/icons: 2.0.3-alpha.0

**Comment by kirkobyte** [comment]
Whoops! I think we should copy the PNG folder into `dist`. I think having users set up their own image loader is a pretty reasonable expectation. If images are kept separate, loading can be deferred to when they're actually rendered on the page. If we base64 transform them, they'll all be included in the main bundle size which is a bit less performant

**Comment by ggdaltoso** [comment]
I think it won't be an issue anymore since we merged #260 

We can reopen this if not!

**Comment by earksiinni** [comment]
Unfortunately, I'm still seeing this error with next 11.0.1, @react95/core 5.5.0, and @react95/icons 2.0.4.

**Comment by earksiinni** [comment]
Sorry, I wrote too soon. I'm actually getting a different error that references the same file as in the original error above:

```
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/foo/node_modules/@react95/icons/cjs/react/Access110.js:12:48)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
/foo/node_modules/@react95/icons/png/Access110_32x32_4.png:1
```

**Comment by earksiinni** [comment]
Ah. I figured out the problem. You need to add `@react95/icons` to the list of transpiled modules in `next.config.js`. My config looks like:

```js
const withFonts = require("next-fonts");
const withTM = require("next-transpile-modules")([
  "@react95/core",
  "@react95/icons",
]);

module.exports = withFonts(withTM());
```

You may want to update the readme.

**Comment by ggdaltoso** [comment]
Hey, @earksiinni 

I'm glad you found the solution so quickly!

What do you think about adding it to [Core's README](https://github.com/React95/React95/tree/master/packages/core#nextjs)? There is a section just for NextJS and it would be great to have your solution there.
